FROM tianon/true
MAINTAINER Benjamin Borbe <bborbe@rocketnews.de>
COPY auth-http-proxy-server /
COPY files/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/auth-http-proxy-server"]
