[[constraint]]
  name = "github.com/jtblin/go-ldap-client"
  source = "https://github.com/bborbe/go-ldap-client.git"
  branch = "master"

[[constraint]]
  name = "go.jona.me/crowd"
  source = "https://github.com/jda/go-crowd.git"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
