#!/bin/sh

set -e

USER="auth-http-proxy"
GROUP="auth-http-proxy"
SERVICE="auth-http-proxy.service"

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke stop $SERVICE >/dev/null || true
fi

exit 0
